import { NavFooter } from "./_ui";
import * as styles from "./_styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const me = {
  id: 100,
  icon: "https://avatars.githubusercontent.com/u/55625375?v=4",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.resetStyle}>
        {children}
        <NavFooter user={me} />
      </body>
    </html>
  );
}
